<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Additional Compiled Classes
	|--------------------------------------------------------------------------
	|
	| Here you may specify additional classes to include in the compiled file
	| generated by the `artisan optimize` command. These should be classes
	| that are included on basically every request into the application.
	|
	*/
    'app/GenSend/Repositories/EloquentRepository.php',
    'app/GenSend/Repositories/EloquentSendRepository.php',
    'app/GenSend/Library/Utils/String.php',
    'app/GenSend/Library/Utils/Number.php',
    'app/GenSend/Validators/Validator.php',
    'app/GenSend/Validators/GenerateFormValidator.php',
    'app/GenSend/Validators/SendFormValidator.php',



);